##  Numpy array operations


In [3]:
import numpy as np

In [4]:
arr=np.array([1, 2, 3, 4, 5])
print("basics slice:", arr[0:3])
print("slice with step:", arr[0:5:2])
print("negative indexing:", arr[-1])


basics slice: [1 2 3]
slice with step: [1 3 5]
negative indexing: 5


In [5]:
arr_2d=np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
print(arr_2d)
print("specific element:", arr_2d[1, 2])
print("entire row:", arr_2d[1:1])
print("entire column:", arr_2d[:, 1])
print("entire row:", arr_2d[1, :]) 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
specific element: 6
entire row: []
entire column: [2 5 8]
entire row: [4 5 6]


### sorting

In [6]:
unsorted=np.array([3, 1, 4, 2, 5])
sorted= np.sort(unsorted)
print("unsorted:", unsorted)
print("sorted:", sorted)
arr_2d_unsorted=np.array([[3, 1, 4],
                            [2, 5, 0],
                            [6, 8, 7]])
print("unsorted 2D array:\n", arr_2d_unsorted)
print("sorted 2D array:\n", np.sort(arr_2d_unsorted, axis=0))  # Sort along columns
print("sorted 2D array (along rows):\n", np.sort(arr_2d_unsorted, axis=1))  # Sort along rows


unsorted: [3 1 4 2 5]
sorted: [1 2 3 4 5]
unsorted 2D array:
 [[3 1 4]
 [2 5 0]
 [6 8 7]]
sorted 2D array:
 [[2 1 0]
 [3 5 4]
 [6 8 7]]
sorted 2D array (along rows):
 [[1 3 4]
 [0 2 5]
 [6 7 8]]


## filter

In [14]:
numbers=np.array([1, 2, 3, 4, 5,6,7,8,9,10])
print(numbers)
even_numbers=numbers[numbers%2==0]
print("even numbers:", even_numbers) 

[ 1  2  3  4  5  6  7  8  9 10]
even numbers: [ 2  4  6  8 10]


## filter with mask

In [15]:
mask=numbers>5
print("numbers greater than 5:", numbers[mask])

numbers greater than 5: [ 6  7  8  9 10]


## fancy indexing vs np.where

In [21]:
indices=[0, 2, 4]
print("elements at indices 0, 2, and 4:", numbers[indices])

##np.where
where_indices = np.where(numbers > 5)
print("indices of numbers greater than 5:", where_indices)
print("numbers greater than 5:", numbers[where_indices])



elements at indices 0, 2, and 4: [1 3 5]
indices of numbers greater than 5: (array([5, 6, 7, 8, 9]),)
numbers greater than 5: [ 6  7  8  9 10]


In [ ]:
condition_array=np.where(numbers>5,numbers,numbers)
print("array with numbers greater than 5 and 0 for others:", condition_array)

array with numbers greater than 5 and 0 for others: [ 0  0  0  0  0  6  7  8  9 10]


## adding and removing

In [26]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
# Element-wise addition
print("Element-wise addition:", arr1 + arr2)
concat_arr = np.concatenate((arr1, arr2))
print("Concatenated array:", concat_arr)

Element-wise addition: [5 7 9]
Concatenated array: [1 2 3 4 5 6]


## array compatibility

In [28]:
a=np.array([1, 2, 3])
b=np.array([4, 5, 6])
c=np.array([7, 8, 9,8])
print("compatibility shapes:",a.shape==b.shape)
print("compatibility shapes:",b.shape==c.shape)

compatibility shapes: True
compatibility shapes: False


In [ ]:
original=np.array([[1,2],[3,4]])
new_row=np.array([[5,6]])

# Adding a new row
with_new_row=np.vstack((original,new_row))
print("Original array:\n", original)
print("Array after adding a new row:\n", with_new_row)
new_column=np.array([[7],[8],[9]])

# Adding a new column
with_new_column=np.hstack((with_new_row,new_column))
print("Array after adding a new column:\n", with_new_column)




Original array:
 [[1 2]
 [3 4]]
Array after adding a new row:
 [[1 2]
 [3 4]
 [5 6]]
Array after adding a new column:
 [[1 2 7]
 [3 4 8]
 [5 6 9]]


In [31]:
## Deleting elements from a NumPy array
arr=np.array([1,2,3,4,5])
deleted_arr=np.delete(arr,2)  # Delete the element at index 2
print("Original array:", arr)
print("Array after deleting element at index 2:", deleted_arr)


Original array: [1 2 3 4 5]
Array after deleting element at index 2: [1 2 4 5]
