## numpy basics
learn about numpy

In [6]:
import numpy as np

### creating array from list



In [7]:
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d)
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


### list vs numpy arr

In [ ]:
py_list=[1,2,3,4 ]

### creating array from scatch    

In [14]:
zeros=np.zeros((4, 4))
print(zeros)
ones=np.ones((4, 4))
print(ones)

full=np.full((4, 4), 7)
print(full)

random=np.random.rand(4, 4)
print(random)

sequence=np.arange(0, 10, 2)
print(sequence)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
[[0.42474175 0.33237037 0.07841404 0.82796099]
 [0.31856439 0.18198734 0.88204829 0.24879733]
 [0.6856831  0.63455951 0.12867792 0.99047788]
 [0.99012833 0.60410073 0.85840557 0.70553669]]
[0 2 4 6 8]


### vector,amtrix and tensor

In [ ]:
vector=np.linspace(0, 1, 2)
print(vector)

matrix=np.eye(4)
print(matrix)

matrix_2=np.array([[1, 2], [3, 4]])
print(matrix_2)

tensor=np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(tensor)

[0. 1.]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1 2]
 [3 4]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### array properties

In [25]:
arr=np.array([1, 2, 3, 4, 5])
print(arr[0])
print("dimension:", arr.ndim)
print("shape:", arr.shape)
print("size:", arr.size)
print("data type:", arr.dtype)
print("item size:", arr.itemsize)

1
dimension: 1
shape: (5,)
size: 5
data type: int64
item size: 8


### array reshaping

In [29]:
arr=np.arange(12)
print(arr)

reshaped_arr=arr.reshape(3, 4)
print(reshaped_arr)

reveled_arr=reshaped_arr.ravel()
print(reveled_arr)

transposed_arr=reshaped_arr.T
print(transposed_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
